site:
  title: Antora Extensions Registry
  url: https://antora-extensions.org
  start_page: registry::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://github.com/antora-supplemental/antora-dark-mode/releases/download/v1.2.0/ui-bundle.zip
    snapshot: true
antora:
  extensions:
    - require: '@antora/lunr-extension'
output:
  dir: ./public/docs
